#!/bin/bash

MAVEN_IMG=maven:3.6.3-jdk-11

docker run --rm \
  -v "$PWD":/workdir -w /workdir \
  -v ~/.m2:/var/maven/.m2 \
  -u $UID \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  $MAVEN_IMG mvn -Duser.home=/var/maven "$@"
