#!/bin/bash

ONOS_IMG=onosproject/onos:2.2.2

docker run -it --rm \
  -e ONOS_APPS \
  -e JAVA_DEBUG_PORT="0.0.0.0:5005" \
  -v /tmp/onos:/root/onos/apache-karaf-4.2.8/data/tmp \
  --network=host \
  $ONOS_IMG "$@"
